package Express.mapper;

import Express.model.po.DemandPo;
import Express.model.po.DemandPoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface DemandPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int insert(DemandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int insertSelective(DemandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    List<DemandPo> selectByExample(DemandPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    DemandPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DemandPo record, @Param("example") DemandPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DemandPo record, @Param("example") DemandPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DemandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DemandPo record);
}