package Express.model.po;

public class AddressPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.campus_id
     *
     * @mbg.generated
     */
    private Integer campusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.collect_address
     *
     * @mbg.generated
     */
    private String collectAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.campus_id
     *
     * @return the value of address.campus_id
     *
     * @mbg.generated
     */
    public Integer getCampusId() {
        return campusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.campus_id
     *
     * @param campusId the value for address.campus_id
     *
     * @mbg.generated
     */
    public void setCampusId(Integer campusId) {
        this.campusId = campusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.collect_address
     *
     * @return the value of address.collect_address
     *
     * @mbg.generated
     */
    public String getCollectAddress() {
        return collectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.collect_address
     *
     * @param collectAddress the value for address.collect_address
     *
     * @mbg.generated
     */
    public void setCollectAddress(String collectAddress) {
        this.collectAddress = collectAddress == null ? null : collectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.company_id
     *
     * @return the value of address.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.company_id
     *
     * @param companyId the value for address.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }
}