package Express.model.po;

import java.time.LocalDateTime;

public class OrderPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sn
     *
     * @mbg.generated
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.demand_id
     *
     * @mbg.generated
     */
    private Long demandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_id
     *
     * @mbg.generated
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.url_check
     *
     * @mbg.generated
     */
    private String urlCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.url_sent
     *
     * @mbg.generated
     */
    private String urlSent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pick_up_time
     *
     * @mbg.generated
     */
    private LocalDateTime pickUpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.collect_time
     *
     * @mbg.generated
     */
    private LocalDateTime collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sent_time
     *
     * @mbg.generated
     */
    private LocalDateTime sentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.satisfy_time
     *
     * @mbg.generated
     */
    private LocalDateTime satisfyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cancel_time
     *
     * @mbg.generated
     */
    private LocalDateTime cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sn
     *
     * @return the value of orders.sn
     *
     * @mbg.generated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sn
     *
     * @param sn the value for orders.sn
     *
     * @mbg.generated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.demand_id
     *
     * @return the value of orders.demand_id
     *
     * @mbg.generated
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.demand_id
     *
     * @param demandId the value for orders.demand_id
     *
     * @mbg.generated
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_id
     *
     * @return the value of orders.receiver_id
     *
     * @mbg.generated
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_id
     *
     * @param receiverId the value for orders.receiver_id
     *
     * @mbg.generated
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_mobile
     *
     * @return the value of orders.receiver_mobile
     *
     * @mbg.generated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_mobile
     *
     * @param receiverMobile the value for orders.receiver_mobile
     *
     * @mbg.generated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.url_check
     *
     * @return the value of orders.url_check
     *
     * @mbg.generated
     */
    public String getUrlCheck() {
        return urlCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.url_check
     *
     * @param urlCheck the value for orders.url_check
     *
     * @mbg.generated
     */
    public void setUrlCheck(String urlCheck) {
        this.urlCheck = urlCheck == null ? null : urlCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.url_sent
     *
     * @return the value of orders.url_sent
     *
     * @mbg.generated
     */
    public String getUrlSent() {
        return urlSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.url_sent
     *
     * @param urlSent the value for orders.url_sent
     *
     * @mbg.generated
     */
    public void setUrlSent(String urlSent) {
        this.urlSent = urlSent == null ? null : urlSent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.deleted
     *
     * @return the value of orders.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.deleted
     *
     * @param deleted the value for orders.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pick_up_time
     *
     * @return the value of orders.pick_up_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPickUpTime() {
        return pickUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pick_up_time
     *
     * @param pickUpTime the value for orders.pick_up_time
     *
     * @mbg.generated
     */
    public void setPickUpTime(LocalDateTime pickUpTime) {
        this.pickUpTime = pickUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.collect_time
     *
     * @return the value of orders.collect_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.collect_time
     *
     * @param collectTime the value for orders.collect_time
     *
     * @mbg.generated
     */
    public void setCollectTime(LocalDateTime collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sent_time
     *
     * @return the value of orders.sent_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sent_time
     *
     * @param sentTime the value for orders.sent_time
     *
     * @mbg.generated
     */
    public void setSentTime(LocalDateTime sentTime) {
        this.sentTime = sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.satisfy_time
     *
     * @return the value of orders.satisfy_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSatisfyTime() {
        return satisfyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.satisfy_time
     *
     * @param satisfyTime the value for orders.satisfy_time
     *
     * @mbg.generated
     */
    public void setSatisfyTime(LocalDateTime satisfyTime) {
        this.satisfyTime = satisfyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cancel_time
     *
     * @return the value of orders.cancel_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cancel_time
     *
     * @param cancelTime the value for orders.cancel_time
     *
     * @mbg.generated
     */
    public void setCancelTime(LocalDateTime cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_create
     *
     * @return the value of orders.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_create
     *
     * @param gmtCreate the value for orders.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_modified
     *
     * @return the value of orders.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_modified
     *
     * @param gmtModified the value for orders.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}