package Express.model.po;

import java.time.LocalDateTime;

public class OrderPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.demand_id
     *
     * @mbg.generated
     */
    private Long demandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_id
     *
     * @mbg.generated
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.url_check
     *
     * @mbg.generated
     */
    private String urlCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.url_sent
     *
     * @mbg.generated
     */
    private String urlSent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.demand_id
     *
     * @return the value of orders.demand_id
     *
     * @mbg.generated
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.demand_id
     *
     * @param demandId the value for orders.demand_id
     *
     * @mbg.generated
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_id
     *
     * @return the value of orders.receiver_id
     *
     * @mbg.generated
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_id
     *
     * @param receiverId the value for orders.receiver_id
     *
     * @mbg.generated
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.url_check
     *
     * @return the value of orders.url_check
     *
     * @mbg.generated
     */
    public String getUrlCheck() {
        return urlCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.url_check
     *
     * @param urlCheck the value for orders.url_check
     *
     * @mbg.generated
     */
    public void setUrlCheck(String urlCheck) {
        this.urlCheck = urlCheck == null ? null : urlCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.url_sent
     *
     * @return the value of orders.url_sent
     *
     * @mbg.generated
     */
    public String getUrlSent() {
        return urlSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.url_sent
     *
     * @param urlSent the value for orders.url_sent
     *
     * @mbg.generated
     */
    public void setUrlSent(String urlSent) {
        this.urlSent = urlSent == null ? null : urlSent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.deleted
     *
     * @return the value of orders.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.deleted
     *
     * @param deleted the value for orders.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_create
     *
     * @return the value of orders.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_create
     *
     * @param gmtCreate the value for orders.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_modified
     *
     * @return the value of orders.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_modified
     *
     * @param gmtModified the value for orders.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}