package Express.model.po;

import java.time.LocalDateTime;

public class VerificationPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.cover_img
     *
     * @mbg.generated
     */
    private String coverImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.content_img
     *
     * @mbg.generated
     */
    private String contentImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.id
     *
     * @return the value of verification.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.id
     *
     * @param id the value for verification.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.user_id
     *
     * @return the value of verification.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.user_id
     *
     * @param userId the value for verification.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.status
     *
     * @return the value of verification.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.status
     *
     * @param status the value for verification.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.cover_img
     *
     * @return the value of verification.cover_img
     *
     * @mbg.generated
     */
    public String getCoverImg() {
        return coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.cover_img
     *
     * @param coverImg the value for verification.cover_img
     *
     * @mbg.generated
     */
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg == null ? null : coverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.content_img
     *
     * @return the value of verification.content_img
     *
     * @mbg.generated
     */
    public String getContentImg() {
        return contentImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.content_img
     *
     * @param contentImg the value for verification.content_img
     *
     * @mbg.generated
     */
    public void setContentImg(String contentImg) {
        this.contentImg = contentImg == null ? null : contentImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.gmt_create
     *
     * @return the value of verification.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.gmt_create
     *
     * @param gmtCreate the value for verification.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.gmt_modified
     *
     * @return the value of verification.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.gmt_modified
     *
     * @param gmtModified the value for verification.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}